title: Dehavilland Ediciones
email: hello@dehavilland.co
description: > # this means to ignore newlines until "baseurl:"
  DeHavilland es una pequeña editorial independiente de Barcelona. Nacida en 2012 a través de la creación de Clift fanzine, nuestro catálogo creció con Heredera y La mansión en llamas a base de aprendizaje, emoción y placer por la configuración de una colección movida por la unión de ilustración y narrativa, mezclando autores y artistas que nos apasionan y que queremos compartir con el universo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dehavilland.co" # the base hostname & protocol for your site

markdown: kramdown
permalink: pretty
timezone: Europe/Madrid

collections:
  authors:
    output: false
  novelties:
    output: true
    permalink: /noticias/:path/
  slides:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "novelties"
    values:
      layout: "novelty"
  -
    scope:
      path: ""
      type: "slides"
    values:
      layout: "default"

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
